# 数据源配置
spring:
  datasource:
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://42.193.2.246:31907/industry_monitoring_standard?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: yjwl2019!@#
  redis:
    database: 12
    # 地址
    host: 42.193.2.246
    # 端口，默认为6379
    port: 30206
    # 密码
    password:

  data:
    mongodb:
      host: 1.14.13.130
      port: 32585
      database: industry-monitoring-standard
      username: industry
      password: yjwlindustry
