# 数据源配置
spring:
  datasource:
    dynamic:
      primary: industryMonitoringStandard
      datasource:
        # 标准产监-生产
        industryMonitoringStandard:
          url: jdbc:mysql://mysql:3306/industry_monitoring_standard?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: yjwl2019!@#
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 一码游贵州-生产（读库）
        oneTravel:
          url: jdbc:mysql://mysql-slave1.yj-guizhou:3306/db_one_travel?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          username: yjymygz
          password: Yj123Ymygz!@#
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 珊瑚礁-生产（读库）
        fxDist:
          url: jdbc:mysql://tx-mysql-slave.yj-fx-distribution:3306/db_dist?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          username: yjfx
          password: Yjfx123!@#
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 景区中心-生产（读库）
        smartTravel:
          url: jdbc:mysql://tx-mysql-slave.yj-fx-distribution:3306/db_smart_travel?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          username: yjfx
          password: Yjfx123!@#
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 酒店中心-生产（读库）
        hotelCenter:
          url: jdbc:mysql://mysql-slave1.yj-guizhou:3306/db_hotel_yjwl?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          username: yjymygz
          password: Yj123Ymygz!@#
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        webStatFilter:
          enabled: true
        statViewServlet:
          enabled: true
          # 设置白名单，不填则允许所有访问
          allow:
          url-pattern: /druid/*
          # 控制台管理用户名和密码
          login-username:
          login-password:
        filter:
          stat:
            enabled: true
            # 慢SQL记录
            log-slow-sql: true
            slow-sql-millis: 2000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true
  redis:
    database: 9
    # 地址
    host: redis
    # 端口，默认为6379
    port: 6379
    # 密码
    password: yjwl2019!@#

#  data:
#    mongodb:
#      host: mongo
#      port: 27017
#      database: industry-monitoring-standard
#      username: industry
#      password: yjwlindustry

# 游客结构-区县大数据接口配置
tourist:
  # 区县大数据平台的请求地址
  districtHost: https://tourism-bigdata.yunjingtech.cn/bigdata-api
  # 区县大数据 参数设置模块中 配置的账号key
  configAccountKey: big_data_account
  # 区县大数据 参数设置模块中 配置的密码key
  configPasswordKey: big_data_password
  # 区县大数据 参数设置模块中 配置的 行政区划编号 key
  configAreaCodeKey: big_data_area_code

# 消息中心
message:
  dictType:
    # 超级管理员数据字典类型
    admin: super_admin_user_id


# 辅助决策
decision:
  dictType:
    missConclusionTextKey: miss_conclusion_text