stages:
  - name: Build-test
    steps:
      - runScriptConfig:
          image: harbor.yunjingtech.cn:30002/yj-base/maven:nexus3
          shellScript: |-
            mvn package -Dmaven.test.skip=true
            ls
  - name: Publish-admin-portal
    steps:
      - publishImageConfig:
          dockerfilePath: portal/admin-portal/Dockerfile
          buildContext: portal/admin-portal/
          tag: yj-guiyang-wenlvzhaoshang/admin-portal:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: harbor.yunjingtech.cn:30002
        env:
          PLUGIN_DEBUG: "true"
          PLUGIN_INSECURE: "true"
          PLUGIN_MIRROR: http://harbor.yunjingtech.cn:30002
    when:
      branch:
        include:
          - prod_wlcy
  - name: Publish-app-portal
    steps:
      - publishImageConfig:
          dockerfilePath: portal/app-portal/Dockerfile
          buildContext: portal/app-portal/
          tag: yj-guiyang-wenlvzhaoshang/app-portal:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: harbor.yunjingtech.cn:30002
        env:
          PLUGIN_DEBUG: "true"
          PLUGIN_INSECURE: "true"
          PLUGIN_MIRROR: http://harbor.yunjingtech.cn:30002
    when:
      branch:
        include:
          - prod_wlcy
  - name: wechat-message-push
    steps:
      - runScriptConfig:
          image: harbor.yunjingtech.cn:30002/yj-base/python:message-prod
          shellScript: python3 /scripts/get_image_name_prod.py
    when:
      branch:
        include:
          - prod_wlcy
timeout: 15