stages:
  - name: Build-test
    steps:
      - runScriptConfig:
          image: harbor.yunjingtech.cn:30002/yj-base/maven:nexus3
          shellScript: |-
            mvn package -Dmaven.test.skip=true
            ls
  - name: Publish-admin-portal
    steps:
      - publishImageConfig:
          dockerfilePath: portal/admin-portal/Dockerfile
          buildContext: portal/admin-portal/
          tag: test-guiyang-wenlvzhaoshang/test-admin-portal:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: harbor.yunjingtech.cn:30002
        env:
          PLUGIN_DEBUG: "true"
          PLUGIN_INSECURE: "true"
          PLUGIN_MIRROR: http://harbor.yunjingtech.cn:30002
    when:
      branch:
        include:
          - test_wlcy
  - name: Deploy-admin-portal
    steps:
      - applyYamlConfig:
          path: portal/admin-portal/deployment.yaml
    when:
      branch:
        include:
          - test_wlcy
  - name: Publish-app-portal
    steps:
      - publishImageConfig:
          dockerfilePath: portal/app-portal/Dockerfile
          buildContext: portal/app-portal/
          tag: test-guiyang-wenlvzhaoshang/test-app-portal:${CICD_EXECUTION_SEQUENCE}
          pushRemote: true
          registry: harbor.yunjingtech.cn:30002
        env:
          PLUGIN_DEBUG: "true"
          PLUGIN_INSECURE: "true"
          PLUGIN_MIRROR: http://harbor.yunjingtech.cn:30002
    when:
      branch:
        include:
          - test_wlcy
  - name: Deploy-app-portal
    steps:
      - applyYamlConfig:
          path: portal/app-portal/deployment.yaml
    when:
      branch:
        include:
          - test_wlcy
timeout: 15