# 数据源配置
spring:
  datasource:
    dynamic:
      primary: industryMonitoringStandard
      datasource:
        # 标准产监-测试
        industryMonitoringStandard:
          url: jdbc:mysql://mysql.test-standard-integrated:3306/industry_monitoring_standard?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: yjwl2019!@#
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 一码游贵州-测试（第一套环境）
        oneTravel:
          url: jdbc:mysql://mysql.test-guizhou:3306/db_one_travel?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Xnh00<>?
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 珊瑚礁-测试（第一套环境）
        fxDist:
          url: jdbc:mysql://mysql.test-fx-distribution:3306/db_dist?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Xnh00<>?
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 景区中心-测试（第一套环境）
        smartTravel:
          url: jdbc:mysql://mysql.test-fx-distribution:3306/db_smart_travel?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Xnh00<>?
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 酒店中心-测试（第一套环境）
        hotelCenter:
          url: jdbc:mysql://mysql.test-hotel:3306/db_hotel?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Xnh00<>?
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        # 初始连接数
        initialSize: 5
        # 最小连接池数量
        minIdle: 10
        # 最大连接池数量
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 配置一个连接在池中最大生存的时间，单位是毫秒
        maxEvictableIdleTimeMillis: 900000
        # 配置检测连接是否有效
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        webStatFilter:
          enabled: true
        statViewServlet:
          enabled: true
          # 设置白名单，不填则允许所有访问
          allow:
          url-pattern: /druid/*
          # 控制台管理用户名和密码
          login-username:
          login-password:
        filter:
          stat:
            enabled: true
            # 慢SQL记录
            log-slow-sql: true
            slow-sql-millis: 2000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true
  redis:
    database: 12
    # 地址
    host: redis.test-standard-integrated
    # 端口，默认为6379
    port: 6379
    # 密码
    password:

  data:
    mongodb:
      host: 1.14.13.130
      port: 32696
      database: industry-monitoring-standard
      username: industry
      password: yjwlindustry

# app消息推送配置
tpns:
  config:
    androidAppId: 1500018471
    androidSecretKey: 2aab961f5af78d8c7cf70b3fcc04ae23
    iosAppId: 1600018472
    iosSecretKey: dc932e7fce0b2ca6943fd2e8cb942dbf
    connectTimeOut: 30
    readTimeOut: 30
    domainUrl: https://api.tpns.tencent.com/

# 短信推送
sms.wo:
  cpcode: AAASIC
  key: b76367f18e4b8871f787e5b07d90c9af
  # templetid: 185409
  # 旅游投诉短信模板
  tourTemplateId:
  # 应急事件短信模板
  emergencyTemplateId:
  url: http://rcsapi.wo.cn:8000/umcinterface/sendtempletmsg
  msg:

# 游客结构-区县大数据接口配置
tourist:
  # 区县大数据平台的请求地址
  districtHost: https://tourism-bigdata.yunjingtech.cn/bigdata-api

# 消息中心
message:
  dictType:
    # 超级管理员数据字典类型
    admin: super_admin_user_id
