apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  namespace: test-standard-industry-monitor
  labels:
    app: admin-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: admin-portal
        args:
        - --spring.profiles.active=test
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: '["deployment:test-standard-industry-monitor:admin-portal"]'
  name: admin-portal
  namespace: test-standard-industry-monitor
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080