apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-portal
  namespace: test-guiyang-wenlvzhaoshang
  labels:
    app: app-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-portal
  template:
    metadata:
      labels:
        app: app-portal
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: app-portal
        args:
        - --spring.profiles.active=test
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8090
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: '["deployment:test-guiyang-wenlvzhaoshang:app-portal"]'
  name: app-portal
  namespace: test-guiyang-wenlvzhaoshang
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090